// Class automatically generated by Dev-C++ New Class wizard
#include <stdio.h>      /* printf, scanf, puts, NULL */
#include <stdlib.h>     /* srand, rand */
#include <time.h>       
#include "Maze.h"
#ifndef MONSTER_H
#define MONSTER_H

#include "Being.h" // inheriting class's header file
#include "Maze.h"
/*
 * No description
 stationary beings 
 
 */
class Monster : public Being
{
	private:

            
    public:
		// class constructor
		Monster();
        void set_placement(Maze, int, int);
		// class destructor
		~Monster();
};

#endif // MONSTER_H
